[key-bindings]
toggle-spaces-bar = "Ctrl+s"
create-space = "Ctrl+n"
edit-current-space = "Ctrl+e"
delete-current-space = "Ctrl+Delete"
select-prev-list-item = "Alt+1"
select-next-list-item = "Alt+2"
find-note = "Ctrl+f"
find-note-in-selected-space = "Ctrl+m"
regenerate-space-avatar = "Ctrl+r"

[appearance]
theme = "theme_dark.toml"

[app]
app-toggle = "F2"
always-on-top = false
hide-window-decorations = false
hide-taskbar-icon = false