[key-bindings]
toggle-spaces-bar = "ControlLeft+keyS"
create-space = "ControlLeft+keyN"
edit-current-space = "ControlLeft+keyE"
delete-current-space = "ControlLeft+Delete"
select-prev-list-item = "AltLeft+Digit1"
select-next-list-item = "AltLeft+Digit2"
find-note = "ControlLeft+keyF"

[appearance]
theme = "theme_dark.toml"

[app]
app-toggle = "F2"