notes_background_color = "#18191d"
notes_border_color = "#18191d"

profile_background_color = "#282e33"
spaces_background_color = "#282e33"

spaces_tools_background_color = "#282e33"
spaces_tools_text_color = "#c6c4af"

messages_info_background_color = "#282e33"
messages_info_text_color = "#ababad"

messages_editor_background_color = "#2d4042"
messages_editor_text_color = "#ababad"