notes_background_color = "#74b4e0"
notes_border_color = "#74b4e0"

profile_background_color = "#ffffff"
spaces_background_color = "#ffffff"

spaces_tools_background_color = "#f1f1f1"
spaces_tools_text_color = "#1d1c1c"

messages_info_background_color = "#ffffff"
messages_info_text_color = "#1d1c1c"

messages_editor_background_color = "#ffffff"
messages_editor_text_color = "#1d1c1c"