[key-bindings]
toggle-spaces-bar = "ControlLeft+keyS"
create-space = "ControlLeft+keyN"
edit-current-space = "ControlLeft+keyE"
delete-current-space = "ControlLeft+Delete"
select-next-space = "AltLeft+Digit2"
select-prev-space = "AltLeft+Digit1"

[appearance]
theme = "theme_dark.toml"

[app]
app-toggle = "F2"
