[key-bindings]
toggle-spaces-bar = "ControlLeft+keyS"
create-space = "ControlLeft+keyN"
edit-current-space = "ControlLeft+keyE"
delete-current-space = "ControlLeft+Delete"
select-next-list-item = "AltLeft+Digit2"
select-prev-list-item = "AltLeft+Digit1"
find-note = "ControlLeft+keyF"
find-note-in-selected-space = "ControlLeft+keyM"

[appearance]
theme = "theme_dark.toml"

[app]
app-toggle = "F2"
