messages_background = "#74b4e0"
messages_border = "#74b4e0"

profile_background = "#ffffff"
spaces_background = "#ffffff"

spaces_tools_background = "#f1f1f1"
spaces_tools_color = "#1d1c1c"

messages_info_background = "#ffffff"
messages_info_color = "#1d1c1c"

messages_editor_background = "#ffffff"
messages_editor_color = "#1d1c1c"