messages_background = "red"
messages_border = "red"

profile_background = "blue"
spaces_background = "#282e33"

spaces_tools_background = "green"
spaces_tools_color = "#c6c4af"

messages_info_background = "#282e33"
messages_info_color = "#ababad"

messages_editor_background = "#282e33"
messages_editor_color = "#ababad"