-- Add migration script here

ALTER TABLE spaces ADD COLUMN is_deleted INTEGER NOT NULL DEFAULT FALSE;
ALTER TABLE spaces ADD COLUMN updated_at TEXT DEFAULT '2024-02-16T23:20:50.52Z';
UPDATE spaces set updated_at = created_at;

ALTER TABLE notes ADD COLUMN is_deleted INTEGER NOT NULL DEFAULT FALSE;
ALTER TABLE notes ADD COLUMN updated_at TEXT DEFAULT '2024-02-16T23:20:50.52Z';
UPDATE notes set updated_at = created_at;

ALTER TABLE files ADD COLUMN created_at TEXT NOT NULL DEFAULT '2024-06-14T22:32:08.134275686Z';
ALTER TABLE files ADD COLUMN updated_at TEXT NOT NULL DEFAULT '2024-06-14T22:32:08.134275686Z';
ALTER TABLE files ADD COLUMN is_deleted INTEGER NOT NULL DEFAULT FALSE;

CREATE TABLE operations (
    id BLOB NOT NULL PRIMARY KEY,
    created_at TEXT NOT NULL,
    operation TEXT NOT NULL
);
