-- Add migration script here

ALTER TABLE spaces ADD COLUMN is_synced INTEGER NOT NULL DEFAULT FALSE;
ALTER TABLE notes ADD COLUMN is_synced INTEGER NOT NULL DEFAULT FALSE;
ALTER TABLE files ADD COLUMN is_synced INTEGER NOT NULL DEFAULT FALSE;
