-- Add migration script here

ALTER TABLE files ADD COLUMN is_deleted INTEGER NOT NULL DEFAULT FALSE;
ALTER TABLE notes ADD COLUMN is_deleted INTEGER NOT NULL DEFAULT FALSE;
ALTER TABLE spaces ADD COLUMN is_deleted INTEGER NOT NULL DEFAULT FALSE;