name: Check
on:
  pull_request:
    branches:
      - main
jobs:
  check:
    name: Check code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1

    - name: 'Add nightly channel'
      run: 'rustup toolchain install nightly'

    - name: 'Add nightly fmt'
      run: 'rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu'

    - name: 'Fmt'
      run: 'cd dataans && cargo +nightly fmt --all -- --check'

    - name: 'Clippy'
      run: 'cd dataans && cargo clippy --all-targets --all -- -D warnings'

    # We do not have tests yet. Uncomment when we have.
    # - name: 'Tests'
    #   run: 'cargo test'