name: Build & Deploy
env:
  DATAANS_SERVER_DOMAIN: dataans.com
on:
  push:
    branches:
    - 'main'
jobs:
  check:
    name: Check code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev javascriptcoregtk-4.1 libsoup-3.0 webkit2gtk-4.1

    - name: 'Add nightly channel'
      run: 'rustup toolchain install nightly'

    - name: 'Add nightly fmt'
      run: 'rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu'

    - name: 'Fmt'
      run: 'cargo +nightly fmt --all -- --check'

    - name: 'Clippy'
      run: 'SQLX_OFFLINE=true cargo clippy --workspace --all-features --all-targets -- -D warnings'

    - name: 'Tests'
      run: 'SQLX_OFFLINE=true cargo test --workspace --all-features'

# Some day I'll set up cross platform (matrix) app build with proper artifacts.
# But currently I don't need it :)
  # deploy:
  #   name: Build app
  #   runs-on: ubuntu-latest
  #   needs: check

  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
